services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #   target: dev

    # command: ['mix', 'phx.server']

    # entrypoint: ./dev.entrypoint.sh

    env_file:
      - .env

    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MIX_ENV=prod

    ports:
      - 4000:4000

    stdin_open: true

    tty: true

    volumes:
      - .:/home/darnoc/app
      - shared-volume:/var/shared

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.4-bullseye

    volumes:
      - db-volume:/var/lib/postgresql/data
      - shared-volume:/var/shared

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-volume: {}
  shared-volume: {}
